project:
    type: website
    output-dir: docs
# author: Alán F. Muñoz
# date: last-modified

language:
    search-text-placeholder: Search

website:
    title: "JUMP documentation and examples"
    repo-url: https://github.com/broadinstitute/2023_12_JUMP_data_only_vignettes
    repo-actions: [edit, source, issue]
    reader-mode: true
    search:
        location: sidebar
        type: overlay
    sidebar:
        style: "floating"
        contents:
            - text: Home
              file: index.md
            - section: How-To Guides
              contents:
                  - auto: "howto/*"
            - section: Explanations
              contents:
                  - auto: "explanations/*"
        tools:
            - icon: github
              href: https://github.com/broadinstitute/2023_12_JUMP_data_only_vignettes

format:
    html:
        default-image-extension: svg
        toc: true
        theme:
            light: flatly
            dark: darkly
        code-fold: false
    ipynb:
        default-image-extension: svg
