[tool.poetry]
name = "jump_stories_myt1"
version = "0.1.0"
description = ""
authors = ["Alan"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
PyYAML = "5.3.1"
# plotly = "4.14.3"
# dvc-s3 = "^2.23.0"
jupyter = "^1.0.0"
scikit-learn = "^1.3.0"
scipy = ">=1.8.1"
matplotlib = "^3.7.3"
seaborn = "^0.12.2"
broad-babel = "^0.1.8"
copairs = {git = "https://github.com/cytomining/copairs.git", rev = "v0.4.0-alpha"}
numpy = "*"
fastcluster = "^1.2.6"
pandas = "*"
pyarrow = "^14.0.1"
joblib = "^1.3.2"
torch = "2.0.0"


[tool.poetry.group.dev.dependencies]
jupytext = "^1.15.2"
ipdb = "^0.13.13"
isort = "^5.12.0"
black = "^23.7.0"
pyflakes = "^3.1.0"
ruff-lsp = "^0.0.48"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
